# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcpq" do
  version "0.0.3"

  on_macos do
    on_arm do
      sha256 "b480520ef40c7553d1b96c2bd426659dde62e6fc829c449f896ed287d69019e3"
      url "https://github.com/Big-Time-Data/mcp-query/releases/download/v#{version}/mcpq_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "166c997f80c8873720bf7941a3702cfe6682a32ab914fed606dc10fa3d7e04f2"
      url "https://github.com/Big-Time-Data/mcp-query/releases/download/v#{version}/mcpq_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "eaff349ef2dfcc4226b91fecb3cc4f5f3503ba6f4b72a9671be19b1cde4b083c"
      url "https://github.com/Big-Time-Data/mcp-query/releases/download/v#{version}/mcpq_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "400dddf416a16f1f849e39be4f5edc148a8d14b1391d392e7a4625268d63fe9b"
      url "https://github.com/Big-Time-Data/mcp-query/releases/download/v#{version}/mcpq_linux_amd64.tar.gz"
    end
  end

  name "mcpq"
  desc "Let an LLM query a customer's warehouse and find the context it needs"
  homepage "https://github.com/big-time-data/mcp-query"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcpq"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mcpq"]
    end
  end

  # No zap stanza required
end
