# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mcpq < Formula
  desc "Let an LLM query a customer's warehouse and find the context it needs"
  homepage "https://github.com/Big-Time-Data/mcp-query"
  version "0.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Big-Time-Data/homebrew-tools/releases/download/v0.0.6/mcpq_darwin_amd64.tar.gz"
      sha256 "a51eb3c47bca9a022a9c58a77fa44d6a9db02ebcfd21e8b47cc520ccb344b7cf"

      define_method(:install) do
        bin.install "mcpq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Big-Time-Data/homebrew-tools/releases/download/v0.0.6/mcpq_darwin_arm64.tar.gz"
      sha256 "b6f55d10d27d7a77b887b86101ffccd89070690eb07c5dc1b759b7ac56140c71"

      define_method(:install) do
        bin.install "mcpq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Big-Time-Data/homebrew-tools/releases/download/v0.0.6/mcpq_linux_amd64.tar.gz"
      sha256 "8d37287e2c5d2ca541e4d4405ac29ad5e83e13b4f61c485610b4636e687f2f91"
      define_method(:install) do
        bin.install "mcpq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Big-Time-Data/homebrew-tools/releases/download/v0.0.6/mcpq_linux_arm64.tar.gz"
      sha256 "199d9d3558f697a275decb54c58fed6486af4efd91dbeecd1253ed1a3bd0e86e"
      define_method(:install) do
        bin.install "mcpq"
      end
    end
  end

  test do
    system "#{bin}/mcpq", "version"
  end
end
