# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mcpq < Formula
  desc "Let an LLM query a customer's warehouse and find the context it needs"
  homepage "https://github.com/Big-Time-Data/mcp-query"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Big-Time-Data/mcp-query/releases/download/v0.0.4/mcpq_darwin_amd64.tar.gz"
      sha256 "d3f29d1bf1c76b678f58331779515d6fdc1c43bd2a4098d696c4d6f5311e7740"

      define_method(:install) do
        bin.install "mcpq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Big-Time-Data/mcp-query/releases/download/v0.0.4/mcpq_darwin_arm64.tar.gz"
      sha256 "e27f6fb006a0e0985c6975e377fbbe03fd8a2141a24f74f2d4a8225d819c8db4"

      define_method(:install) do
        bin.install "mcpq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Big-Time-Data/mcp-query/releases/download/v0.0.4/mcpq_linux_amd64.tar.gz"
      sha256 "1349a20809566348e7241b85f5632a6eeb567f77e2b43d35e32b37193d182f56"
      define_method(:install) do
        bin.install "mcpq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Big-Time-Data/mcp-query/releases/download/v0.0.4/mcpq_linux_arm64.tar.gz"
      sha256 "4e4e9e44f167dbeb28928caad5240f3f2cffe059e24b22c2e0a4d6d5a35f8cfa"
      define_method(:install) do
        bin.install "mcpq"
      end
    end
  end

  test do
    system "#{bin}/mcpq", "version"
  end
end
